kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".containerd.runtimes."crun"]
    runtime_type = "io.containerd.runc.v2"
    pod_annotations = [
      "*.wasm.*",
      "wasm.*",
      "module.wasm.image/*",
      "*.module.wasm.image",
      "module.wasm.image/variant.*" ]
  [plugins."io.containerd.grpc.v1.cri".containerd.runtimes."crun".options]
    BinaryName = "/usr/local/sbin/crun"
    SystemdCgroup = false
